### ISSUE TITLE
New Variant

### ISSUE THREAD

**Issue by coachkeith** [33Infinity/Chessercizes#10]
Vladimir Kramnik just proposed a new variant in this article on chess.com. I like it! No-Castling Chess.

https://www.chess.com/article/view/no-castling-chess-kramnik-alphazero

**Comment by ackerman7** [comment]
Interesting! I can add it in there!

**Comment by ackerman7** [comment]
Added it!

**Comment by coachkeith** [comment]
Awesome! Any time a former world champion endorses a variant, it’s a free spokesman/sponsor for us.
